import { Room, HousekeepingTask, NotificationLog } from './types';

export const INITIAL_ROOMS: Room[] = [
  {
    id: 'room_401',
    roomNumber: '401',
    floor: 4,
    category: 'Deluxe Room',
    pricePerNight: 5000,
    viewType: 'City',
    areaSqM: 30,
    balcony: false,
    bathtub: false,
    bedType: 'King',
    maxGuests: 2,
    amenities: ['Wi-Fi 6', 'Smart TV 55"', 'Nespresso Machine', 'Work Desk', 'Rain Shower'],
    images: [
      'https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80'
    ],
    status: 'READY',
    isBooked: false,
    gridX: 10,
    gridY: 20,
  },
  {
    id: 'room_402',
    roomNumber: '402',
    floor: 4,
    category: 'Deluxe Room',
    pricePerNight: 5000,
    viewType: 'Garden',
    areaSqM: 31,
    balcony: true,
    bathtub: false,
    bedType: 'King',
    maxGuests: 2,
    amenities: ['Wi-Fi 6', 'Smart TV 55"', 'Garden View Balcony', 'Mini Bar', 'Rain Shower'],
    images: [
      'https://images.unsplash.com/photo-1566665797739-1674de7a421a?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=800&q=80'
    ],
    status: 'DIRTY',
    isBooked: true,
    gridX: 40,
    gridY: 20,
  },
  {
    id: 'room_403',
    roomNumber: '403',
    floor: 4,
    category: 'Deluxe Room',
    pricePerNight: 5000,
    viewType: 'Pool',
    areaSqM: 32,
    balcony: true,
    bathtub: true,
    bedType: 'King',
    maxGuests: 2,
    amenities: ['Wi-Fi 6', 'Smart TV 55"', 'Pool View Balcony', 'Deep Soak Bathtub', 'Nespresso Machine', 'Mini Bar'],
    images: [
      'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=800&q=80'
    ],
    status: 'DIRTY',
    isBooked: true,
    gridX: 70,
    gridY: 20,
  },
  {
    id: 'room_404',
    roomNumber: '404',
    floor: 4,
    category: 'Ocean View Suite',
    pricePerNight: 8500,
    viewType: 'Ocean',
    areaSqM: 48,
    balcony: true,
    bathtub: true,
    bedType: 'King',
    maxGuests: 3,
    amenities: ['Panoramic Ocean Balcony', 'Jacuzzi Bathtub', 'Living Lounge Area', 'Wi-Fi 6', 'Premium Soundbar', 'Pillow Menu'],
    images: [
      'https://images.unsplash.com/photo-1591088398332-8a7791972843?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80'
    ],
    status: 'CLEANING',
    isBooked: true,
    gridX: 70,
    gridY: 60,
  },
  {
    id: 'room_301',
    roomNumber: '301',
    floor: 3,
    category: 'Deluxe Room',
    pricePerNight: 4800,
    viewType: 'City',
    areaSqM: 29,
    balcony: false,
    bathtub: false,
    bedType: 'Twin Beds',
    maxGuests: 2,
    amenities: ['Wi-Fi 6', 'Twin Single Beds', 'Work Desk', 'Rain Shower'],
    images: [
      'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=800&q=80'
    ],
    status: 'READY',
    isBooked: false,
    gridX: 10,
    gridY: 20,
  },
  {
    id: 'room_302',
    roomNumber: '302',
    floor: 3,
    category: 'Deluxe Room',
    pricePerNight: 4900,
    viewType: 'Garden',
    areaSqM: 30,
    balcony: true,
    bathtub: false,
    bedType: 'Queen',
    maxGuests: 2,
    amenities: ['Wi-Fi 6', 'Queen Size Bed', 'Garden Terrace', 'Mini Bar'],
    images: [
      'https://images.unsplash.com/photo-1566665797739-1674de7a421a?auto=format&fit=crop&w=800&q=80'
    ],
    status: 'INSPECTION',
    isBooked: true,
    gridX: 40,
    gridY: 20,
  },
  {
    id: 'room_303',
    roomNumber: '303',
    floor: 3,
    category: 'Premium Suite',
    pricePerNight: 7500,
    viewType: 'Pool',
    areaSqM: 42,
    balcony: true,
    bathtub: true,
    bedType: 'King',
    maxGuests: 3,
    amenities: ['Poolside View', 'Marble Bathtub', 'Private Terrace', 'Cocktail Bar', 'Wi-Fi 6'],
    images: [
      'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80'
    ],
    status: 'READY',
    isBooked: false,
    gridX: 70,
    gridY: 20,
  }
];

export const INITIAL_TASKS: HousekeepingTask[] = [
  {
    id: 'task_403',
    roomId: 'room_403',
    roomNumber: '403',
    floor: 4,
    category: 'Deluxe Room',
    status: 'DIRTY',
    priority: 'URGENT',
    checkoutTime: '11:00 AM',
    nextCheckInTime: '12:00 PM',
    isEarlyCheckIn: true,
    cleaningEstMinutes: 35,
    bufferMinutesRemaining: 15,
    assignedStaff: 'Sunita P.',
    notes: '⚡ PAID EARLY CHECK-IN REQUESTED (12:00 PM arrival). Needs urgent turnover!',
    updatedAt: new Date().toISOString()
  },
  {
    id: 'task_402',
    roomId: 'room_402',
    roomNumber: '402',
    floor: 4,
    category: 'Deluxe Room',
    status: 'DIRTY',
    priority: 'HIGH',
    checkoutTime: '10:30 AM',
    nextCheckInTime: '01:00 PM',
    isEarlyCheckIn: false,
    cleaningEstMinutes: 40,
    bufferMinutesRemaining: 45,
    assignedStaff: 'Ramesh K.',
    notes: 'Standard check-in at 1:00 PM.',
    updatedAt: new Date().toISOString()
  },
  {
    id: 'task_404',
    roomId: 'room_404',
    roomNumber: '404',
    floor: 4,
    category: 'Ocean View Suite',
    status: 'CLEANING',
    priority: 'NORMAL',
    checkoutTime: '09:45 AM',
    nextCheckInTime: '03:00 PM',
    isEarlyCheckIn: false,
    cleaningEstMinutes: 50,
    bufferMinutesRemaining: 140,
    assignedStaff: 'Anil M.',
    notes: 'Deep clean in progress.',
    updatedAt: new Date().toISOString()
  },
  {
    id: 'task_302',
    roomId: 'room_302',
    roomNumber: '302',
    floor: 3,
    category: 'Deluxe Room',
    status: 'INSPECTION',
    priority: 'NORMAL',
    checkoutTime: '10:00 AM',
    nextCheckInTime: '02:30 PM',
    isEarlyCheckIn: false,
    cleaningEstMinutes: 30,
    bufferMinutesRemaining: 120,
    assignedStaff: 'Ramesh K.',
    notes: 'Cleaning completed. Awaiting supervisor inspection.',
    updatedAt: new Date().toISOString()
  }
];

export const INITIAL_NOTIFICATIONS: NotificationLog[] = [
  {
    id: 'notif_101',
    type: 'SMS',
    recipient: 'Sunita P. (+91 98765 11111)',
    message: '⚡ URGENT DISPATCH: Room 403 has purchased Early Check-in (12:00 PM). Please clean & inspect immediately.',
    timestamp: new Date().toISOString()
  },
  {
    id: 'notif_102',
    type: 'WHATSAPP',
    recipient: 'Ramesh K. (+91 98765 22222)',
    message: '📋 Shift Task Update: Room 402 assigned for 1:00 PM arrival.',
    timestamp: new Date().toISOString()
  }
];
